version: "3"

services:
  mysql:
    image: mysql:8.0
    volumes:
      - /home/commojun/k0smysql:/var/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: k0smysqlroot!
      TZ: "Asia/Tokyo"
    restart: always
    logging:
      options:
        max-file: "1"
        max-size: 10m
