apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-pi
spec:
  k0s:
    version: v1.23.6+k0s.1
  hosts:
  - role: controller
    os: debian
    ssh:
      address: pi51.local
      user: pi
      keyPath: ~/.ssh/id_rsa
  - role: worker
    os: debian
    ssh:
      address: pi52.local
      user: pi
      keyPath: ~/.ssh/id_rsa
  - role: worker
    os: debian
    ssh:
      address: pi53.local
      user: pi
      keyPath: ~/.ssh/id_rsa
