apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-pi
spec:
  k0s:
    version: v1.24.9+k0s.0
  hosts:
  - role: controller+worker
    os: debian
    ssh:
      address: pi41.local
      user: commojun
      keyPath: ~/.ssh/id_rsa
  - role: worker
    os: debian
    ssh:
      address: pi31.local
      user: commojun
      keyPath: ~/.ssh/id_rsa
  - role: worker
    os: debian
    ssh:
      address: pi32.local
      user: commojun
      keyPath: ~/.ssh/id_rsa
  - role: worker
    os: debian
    ssh:
      address: pi33.local
      user: commojun
      keyPath: ~/.ssh/id_rsa
