apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-pi
spec:
  k0s:
    version: v1.27.2+k0s.0
    dynamicConfig: true
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: ClusterConfig
      spec:
        storage:
          type: kine
          kine:
            dataSource: mysql://root:k0smysqlroot!@tcp(192.168.10.41)/kine
  hosts:
  - role: controller+worker
    noTaints: true
    os: debian
    ssh:
      address: 192.168.10.41
      user: commojun
      keyPath: ~/.ssh/id_rsa
  - role: worker
    os: debian
    ssh:
      address: 192.168.10.31
      user: commojun
      keyPath: ~/.ssh/id_rsa
  - role: worker
    os: debian
    ssh:
      address: 192.168.10.32
      user: commojun
      keyPath: ~/.ssh/id_rsa
  - role: worker
    os: debian
    ssh:
      address: 192.168.10.33
      user: commojun
      keyPath: ~/.ssh/id_rsa
